version: '3.7'

services:
  dc_db:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    command:
      --explicit_defaults_for_timestamp=1
      --innodb-use-native-aio=0
      --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - 3312:3306
    environment:
      MYSQL_DATABASE: dc_back_db
      MYSQL_ROOT_USER: dc_dev
      MYSQL_USER: dc_dev
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret